[package]
name = "abs"
version = "0.1.0"
authors = ["ariririri <fatal.t.h.f.flydream.bamboo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
